InputFileFolder: 'fixtures/pcap_files/'
ResultFileFolder: 'fixtures/results/'
ResultFileDelimiter: ','
EtherTypeDataFilePath: 'core/static/ether_type.json'
IpProtocolDataFilePath: 'core/static/ip_protocols.json'
ManufFilePath: 'core/static/manuf'
TcpFlagDataFilePath: 'core/static/tcp_flags_data.json'
TcpPortsFilePath: 'core/static/layer4_port_data.json'
p0f_wd: 'core/bin'
p0f_executable: './p0f'
use_numeric_values: false
